blank_issues_enabled: false
contact_links:
  - name: Feature Request ğŸ’¡
    url: https://github.com/wavelog/wavelog/discussions/new?category=ideas
    about: Suggest new features or improvements
  - name: Setup & Usage Questions â“ğŸ’¬
    url: https://github.com/wavelog/wavelog/discussions/new?category=q-a
    about: For setup help and general questions